// dashdig-widget/src/integrations/vue/DashdigWidget.vue
<script setup lang="ts">
/**
 * DashDig Widget - Vue 3 Component
 * Embeddable analytics widget as a Vue 3 component
 */

import { onMounted, onUnmounted, ref } from 'vue';
import DashdigWidget from '../../core/widget';
import type { DashdigConfig } from '../../core/widget';

/**
 * Component props
 */
interface Props {
  apiKey: string;
  position?: 'bottom-right' | 'bottom-left';
  theme?: 'light' | 'dark';
  autoShow?: boolean;
  apiUrl?: string;
}

// Define props with defaults
const props = withDefaults(defineProps<Props>(), {
  position: 'bottom-right',
  theme: 'light',
  autoShow: true
});

/**
 * Component emits
 */
interface Emits {
  (event: 'load'): void;
  (event: 'error', error: Error): void;
}

const emit = defineEmits<Emits>();

// Widget instance reference
const widget = ref<DashdigWidget | null>(null);

/**
 * Initialize widget on component mount
 */
onMounted(() => {
  try {
    // Create widget configuration
    const config: DashdigConfig = {
      apiKey: props.apiKey,
      position: props.position,
      theme: props.theme,
      autoShow: props.autoShow,
      apiUrl: props.apiUrl
    };

    // Create widget instance
    widget.value = new DashdigWidget(config);

    // Emit load event
    emit('load');
  } catch (error) {
    // Emit error event
    if (error instanceof Error) {
      emit('error', error);
    } else {
      emit('error', new Error('Unknown error initializing DashDig widget'));
    }
    console.error('[DashDig Vue] Widget initialization error:', error);
  }
});

/**
 * Cleanup widget on component unmount
 */
onUnmounted(() => {
  if (widget.value) {
    try {
      widget.value.destroy();
      widget.value = null;
    } catch (error) {
      console.error('[DashDig Vue] Widget cleanup error:', error);
    }
  }
});

/**
 * Expose methods for template refs
 */
defineExpose({
  widget,
  show: () => widget.value?.show(),
  hide: () => widget.value?.hide(),
  track: (event: string, data?: Record<string, any>) => widget.value?.track(event, data)
});
</script>

<template>
  <!-- Widget appends to body via Shadow DOM, no template needed -->
</template>

<style scoped>
/* No styles needed - widget is rendered outside component tree */
</style>

// dashdig-widget/src/integrations/react/DashdigWidget.tsx
/**
 * DashDig Widget - React Component
 * Embeddable analytics widget as a React component
 */

import { useEffect, useRef } from 'react';
import DashdigWidget from '../../core/widget';
import type { DashdigConfig } from '../../core/widget';

/**
 * Props for the DashdigWidget React component
 */
export interface DashdigWidgetProps {
  /** API key for authentication (required) */
  apiKey: string;
  /** Widget position on screen */
  position?: 'bottom-right' | 'bottom-left';
  /** Widget theme */
  theme?: 'light' | 'dark';
  /** Auto-show widget on mount */
  autoShow?: boolean;
  /** Callback fired when widget successfully loads */
  onLoad?: () => void;
  /** Callback fired when widget encounters an error */
  onError?: (error: Error) => void;
}

/**
 * DashDig Widget React Component
 * 
 * Renders an analytics widget that tracks user interactions.
 * The widget is appended to document.body and managed through Shadow DOM.
 * 
 * @param props - Component props
 * @returns null (widget renders outside React tree)
 * 
 * @example
 * ```tsx
 * import { DashdigWidget } from '@dashdig/widget/react';
 * 
 * function App() {
 *   return (
 *     <DashdigWidget
 *       apiKey="your-api-key"
 *       position="bottom-right"
 *       theme="light"
 *       autoShow={true}
 *       onLoad={() => console.log('Widget loaded')}
 *       onError={(error) => console.error('Widget error:', error)}
 *     />
 *   );
 * }
 * ```
 */
export const DashdigReactWidget: React.FC<DashdigWidgetProps> = ({
  apiKey,
  position,
  theme,
  autoShow,
  onLoad,
  onError
}) => {
  // Store widget instance reference
  const widgetRef = useRef<DashdigWidget | null>(null);

  useEffect(() => {
    // Initialize widget
    try {
      // Create widget configuration
      const config: DashdigConfig = {
        apiKey,
        position,
        theme,
        autoShow
      };

      // Instantiate widget
      widgetRef.current = new DashdigWidget(config);

      // Call onLoad callback if provided
      if (onLoad) {
        onLoad();
      }
    } catch (error) {
      // Call onError callback if provided
      if (onError && error instanceof Error) {
        onError(error);
      } else {
        console.error('[DashDig React] Widget initialization error:', error);
      }
    }

    // Cleanup function - destroy widget on unmount
    return () => {
      if (widgetRef.current) {
        try {
          widgetRef.current.destroy();
          widgetRef.current = null;
        } catch (error) {
          console.error('[DashDig React] Widget cleanup error:', error);
        }
      }
    };
  }, [apiKey, position, theme, autoShow, onLoad, onError]);

  // Widget renders outside React tree (appends to body)
  return null;
};

// Set display name for debugging
DashdigReactWidget.displayName = 'DashdigWidget';

export default DashdigReactWidget;
